name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Run tests
      run: docker run --rm my-app

    - name: Format check
      run: docker run --rm my-app bash -c "./.github/workflows/format_check.sh"
