name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull eiphyusinn/my-app:latest

    - name: Run tests
      run: docker run --gpus all -it --rm eiphyusinn/my-app:latest

    - name: Format check
      run: docker run --rm eiphyusinn/my-app:latest bash -c "./.github/workflows/format_check.sh"
